from flask import Flask, render_template, make_response, redirect, url_for
import datetime

app = Flask(__name__)

@app.route('/home')
def home():
    now = datetime.datetime.now()
    return render_template('home_basic_rendering.html',curr_now=now)

@app.route('/about')
def about():
    headers={
        'content-Type':'application/json'
    }
    return make_response('This reponse is generated by Make Response',201,headers)

@app.route('/base')
def base():
    return redirect('/home')

@app.route('/contact')
def contact():
    return redirect(url_for('about',username='Er. Arshvir'))


if __name__ == ('__main__'):
    app.run(debug=True)